services:
  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #     # args:
  #     #   - NEXT_PUBLIC_API_URL=http://backend:8080
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - resumewriter
  #   depends_on:
  #     - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    # environment:
    #   - GOOGLE_REDIRECT_URI=http://backend:8080/oauth/google/callback
    networks:
      - resumewriter
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - resumewriter

networks:
  resumewriter:
    driver: bridge

volumes:
  mysql_data: